final_project_django/final_project_django/urls.py
from django.contrib import admin
from django.urls import path, re_path

from final_project_app.views import HomeView, RegisterView, LoginView, LogoutView, ChangePasswordView, \
    ChooseTheOptionsView, PlayView, GamesDetailsView, GamesView

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', HomeView.as_view(), name="home"),
    re_path(r'^home/$', HomeView.as_view(), name="home"),
    re_path(r'^register/$', RegisterView.as_view(), name="register"),
    re_path(r'^login/$', LoginView.as_view(), name="log_in"),
    re_path(r'^logout/$', LogoutView.as_view(), name="log_out"),
    re_path(r'^change_password/(?P<user_id>\d+)/$', ChangePasswordView.as_view(), name="change_password"),
    re_path(r'^choose_the_options/(?P<user_id>\d+)/$', ChooseTheOptionsView.as_view(), name="choose_options"),
    re_path(r'^play/(?P<game_id>\d+)/$', PlayView.as_view(), name="play"),
    re_path(r'^games_details/(?P<game_id>\d+)/$', GamesDetailsView.as_view(), name="game_details"),
    re_path(r'^games/(?P<user_id>\d+)/$', GamesView.as_view(), name="games"),
]

final_project_django/final_project_app/models.py
from django.contrib.auth.models import User
from django.db import models


class Game(models.Model):
    name = models.CharField(max_length=64, default="Enter game name")
    date = models.DateTimeField(auto_now=True)
    operator = models.CharField(max_length=1)
    range1_min = models.IntegerField()
    range1_max = models.IntegerField()
    range2_min = models.IntegerField()
    range2_max = models.IntegerField()
    number_of_correct_answers = models.IntegerField(default=0)
    number_of_wrong_answers = models.IntegerField(default=0)
    is_game_ended = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return f"Operator: {self.operator}"


class GameAnswers(models.Model):
    first_factor = models.IntegerField()
    second_factor = models.IntegerField()
    answer = models.IntegerField(null=True)
    correct_answer = models.IntegerField()
    was_this_answer_correct = models.BooleanField(null=True)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__(self):
        return f"First factor: {self.first_factor} Second factor: {self.first_factor}"

final_project_django/final_project_app/forms.py
import django.forms as forms
from django.core.exceptions import ValidationError
from django.forms import Select


def passwords(cleaned_data):
    if cleaned_data['password'] != cleaned_data['password_again']:
        raise ValidationError('Passwords do not match.')
    return cleaned_data


class RegisterForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)
    password_again = forms.CharField(widget=forms.PasswordInput)
    username = forms.CharField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()

    def clean(self):
        cleaned_data = super().clean()
        return passwords(cleaned_data)


class LoginForm(forms.Form):
    login = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class ChangePasswordForm(forms.Form):
    password = forms.CharField(label='New password.', widget=forms.PasswordInput)
    password_again = forms.CharField(label='Repeat password.', widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        return passwords(cleaned_data)


OPERATORS = (
    ('+', '+'),
    ('-', '-'),
    ('*', '*'),
    ('/', '/'),
    ('%', '%'),
)


class OptionsForm(forms.Form):
    operation = forms.ChoiceField(choices=OPERATORS, widget=Select())
    maximum_number_of_first_factor = forms.IntegerField()
    minimum_number_of_first_factor = forms.IntegerField()
    maximum_number_of_second_factor = forms.IntegerField()
    minimum_number_of_second_factor = forms.IntegerField()

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['maximum_number_of_first_factor'] < cleaned_data['minimum_number_of_first_factor'] or \
                cleaned_data['maximum_number_of_second_factor'] < cleaned_data['minimum_number_of_second_factor']:
            raise ValidationError('The minimum number can not be greater than the maximum number.')
        return cleaned_data


class PlayForm(forms.Form):
    answer = forms.IntegerField(required=False)
    answer_id = forms.IntegerField(widget=forms.HiddenInput())


class NameForGameForm(forms.Form):
    name_of_this_game = forms.CharField(max_length=64)

final_project_django/final_project_app/views.py
from random import randint

from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.auth.models import Group
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError
from django.shortcuts import render, redirect
from django.views import View

from .forms import RegisterForm, LoginForm, ChangePasswordForm, OptionsForm, PlayForm, NameForGameForm
from .models import Game, GameAnswers

User = get_user_model()


class HomeView(View):
    def get(self, request):
        return render(request, "final_project_app/base.html")


class RegisterView(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, "final_project_app/register.html", {'form': form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            try:
                new_user = User.objects.create_user(password=request.POST.get('password'),
                                                    username=request.POST.get('username'),
                                                    first_name=request.POST.get('first_name'),
                                                    last_name=request.POST.get('last_name'),
                                                    email=request.POST.get('email'))
            except IntegrityError:
                return render(request, "final_project_app/register.html",
                              {'form': form, 'error': 'This user already exists.'})
            normal_user_group = Group.objects.get(name='normal_users')
            normal_user_group.user_set.add(new_user)
            return redirect('/home')
        else:
            return render(request, "final_project_app/register.html", {'form': form})


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, "final_project_app/login.html", {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['login'], password=form.cleaned_data['password'])
            if user:
                login(request, user)
                return redirect('/home')
            else:
                return render(request, "final_project_app/login.html",
                              {'form': form, 'error': "Incorrect login or password."})
        else:
            return render(request, "final_project_app/login.html", {'form': form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('/home')


class ChangePasswordView(View):
    def get(self, request, user_id):
        form = ChangePasswordForm()
        return render(request, 'final_project_app/change_password.html', {'form': form})

    def post(self, request, user_id):
        form = ChangePasswordForm(request.POST)
        try:
            user = User.objects.get(pk=user_id)
        except ObjectDoesNotExist:
            return render(request, 'final_project_app/change_password.html',
                          {'form': form, 'error': 'User with this id does not exist.'})
        if form.is_valid():
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('/home')
        else:
            return render(request, 'final_project_app/change_password.html', {'form': form})


class ChooseTheOptionsView(View):
    def get(self, request, user_id):
        form = OptionsForm()
        return render(request, 'final_project_app/confirm_options.html', {'form': form})

    def post(self, request, user_id):
        form = OptionsForm(request.POST)

        if form.is_valid():
            game = Game.objects.create(operator=form.cleaned_data['operation'],
                                       range1_min=form.cleaned_data['minimum_number_of_first_factor'],
                                       range1_max=form.cleaned_data['maximum_number_of_first_factor'],
                                       range2_min=form.cleaned_data['minimum_number_of_second_factor'],
                                       range2_max=form.cleaned_data['maximum_number_of_second_factor'],
                                       user=User.objects.get(pk=user_id))
            return redirect('play', game_id=game.id)
        else:
            return render(request, 'final_project_app/confirm_options.html', {'form': form})


class PlayView(View):
    def get(self, request, game_id):
        game = Game.objects.get(pk=game_id)
        answer_possible_wrong = game.gameanswers_set.last()
        if answer_possible_wrong is None:
            class FakeObj:
                def __init__(self, answer):
                    self.answer = answer

            answer_possible_wrong = FakeObj("fake_answer")
        if answer_possible_wrong.answer is None:
            answer = answer_possible_wrong
            form = PlayForm({'answer_id': answer.id})
            ctx = {
                'form': form,
                'operator': game.operator,
                'first': answer.first_factor,
                'second': answer.second_factor,
                'answer_id': answer.id
            }
        else:
            first = randint(game.range1_min, game.range1_max)
            second = randint(game.range2_min, game.range2_max)
            op = game.operator
            if op == "+":
                correct_answer = first + second
            elif op == "-":
                correct_answer = first - second
            elif op == "*":
                correct_answer = first * second
            elif op == "/":
                correct_answer = first / second
            elif op == "%":
                correct_answer = first % second
            answer = GameAnswers.objects.create(first_factor=first, second_factor=second, game=game,
                                                correct_answer=correct_answer)
            form = PlayForm({'answer_id': answer.id})
            ctx = {
                'form': form,
                'operator': op,
                'first': first,
                'second': second,
                'answer_id': answer.id
            }
        return render(request, 'final_project_app/play.html', ctx)

    def post(self, request, game_id):
        form = PlayForm(request.POST)
        if form.is_valid():
            stop = request.POST.get('btn')
            object_answer = GameAnswers.objects.get(pk=form.cleaned_data['answer_id'])
            if stop == 'Stop':
                object_answer.delete()
                game = Game.objects.get(pk=game_id)
                game.is_game_ended = True
                game.save()
                return redirect('game_details', game_id=game_id)
            user_answer = form.cleaned_data['answer']
            if user_answer is None:
                form.add_error('answer', "This field is required.")
                ctx = {
                    'form': form,
                    'operator': request.POST.get('operator'),
                    'first': request.POST.get('first'),
                    'second': request.POST.get('second'),
                    'answer_id': request.POST.get('answer_id'),
                    'error': "This field is required."
                }
                return render(request, 'final_project_app/play.html', ctx)
            object_answer.answer = user_answer
            game = Game.objects.get(pk=game_id)
            if user_answer == object_answer.correct_answer:
                game.number_of_correct_answers += 1
                object_answer.was_this_answer_correct = True
            else:
                game.number_of_wrong_answers += 1
                object_answer.was_this_answer_correct = False
            object_answer.save()
            game.save()
            return redirect('play', game_id=game_id)
        else:
            ctx = {
                'form': form,
                'operator': request.POST.get('operator'),
                'first': request.POST.get('first'),
                'second': request.POST.get('second'),
                'answer_id': request.POST.get('answer_id'),
                'error': "This is not valid a number."
            }
            return render(request, 'final_project_app/play.html', ctx)


class GamesDetailsView(View):
    def get(self, request, game_id):
        form = NameForGameForm()
        game = Game.objects.get(pk=game_id)
        correct_answers = game.number_of_correct_answers
        wrong_answers = game.number_of_wrong_answers
        try:
            precision = round(correct_answers / (correct_answers + wrong_answers) * 100, 2)
        except ZeroDivisionError:
            precision = 0.0
        answers = game.gameanswers_set.all()
        ctx = {
            'operator': game.operator,
            'range1_min': game.range1_min,
            'range1_max': game.range1_max,
            'range2_min': game.range2_min,
            'range2_max': game.range2_max,
            'number_of_correct_answers': correct_answers,
            'number_of_wrong_answers': wrong_answers,
            'precision': precision,
            'user_id': game.user,
            'date': game.date,
            'name': game.name,
            'form': form,
            'answers': answers,
        }
        return render(request, 'final_project_app/game_details.html', ctx)

    def post(self, request, game_id):
        form = NameForGameForm(request.POST)

        if form.is_valid():
            game = Game.objects.get(pk=game_id)
            game.name = form.cleaned_data['name_of_this_game']
            game.save()
            return redirect('game_details', game_id=game.id)

        else:
            return render(request, 'final_project_app/game_details.html',
                          {'form': form, 'error': "Something went wrong"})


class GamesView(View):
    def get(self, request, user_id):
        games = Game.objects.filter(user=user_id)

final_project_django/final_project_app/templates/final_project_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}BrainMath{% endblock %} | BrainMath</title>
</head>
<body>
<div class="navigation-flex">
    <a href="{% url 'home' %}">
        <header class="header">Brain<span>Math</span></header>
    </a>
    <nav>
        {% if user.is_authenticated %}
            <a class="nav_button" href="{% url 'games' user.id %}">My games</a>
            <a class="nav_button" href="{% url 'change_password' user.id %}">Change password</a>
            <a class="nav_button" href="{% url 'log_out' %}">Log Out</a>
        {% else %}
            <a class="nav_button" href="{% url 'log_in' %}">Log In</a>
            <a class="nav_button" href="{% url 'register' %}">Sign Up</a>
        {% endif %}
    </nav>
</div>
{% block content %}
    {% if user.is_authenticated %}
        <div class="center">
            <a class="play" href="{% url 'choose_options' user.id %}">Let's play</a>
        </div>
    {% endif %}
{% endblock %}
</body>
</html>

final_project_django/final_project_app/templates/final_project_app/change_password.html
{% extends 'final_project_app/base.html' %}
{% block title %}Change password{% endblock %}
{% block content %}
    <div class="password_flex">
        <div class="password_container">
            <form method="post">
                {% csrf_token %}

                <div class="test"><p class="answer">Change Password</p></div>
                <div class="form_error">
                    {{ error }}
                    {% if form.errors %}
                        {% for error in form.non_field_errors %}
                            <p class="label-danger">{{ error|escape }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
                <p><label for="id_password">New password.</label> <input class="input" type="password"
                                                                         name="password"
                                                                         required id="id_password"></p>
                <p><label for="id_password_again">Repeat password.</label> <input class="input" type="password"
                                                                                  name="password_again" required
                                                                                  id="id_password_again"></p>
                <button type="submit" class="submit">Confirm options</button>
            </form>
        </div>
    </div>
    {#    <form method="post">#}
    {#        {% csrf_token %}#}
    {#        {{ form.as_p }}#}
    {#        <input type="submit" value="Change password">#}
    {#    </form>#}
{% endblock %}

final_project_django/final_project_app/templates/final_project_app/confirm_options.html
{% extends 'final_project_app/base.html' %}
{% block title %}Choose options{% endblock %}
{% block content %}
    <div class="options">
        <form method="post">
            {% csrf_token %}
            <p class="elo"><label for="id_operation_0">Operation</label>
            <div class="form_error">
                {{ error }}
                {% if form.errors %}
                    {% for error in form.non_field_errors %}
                        <p class="label-danger">{{ error|escape }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <ul id="id_operation">
                <div class="div_radio">
                    <div class="ball">
                        <label for="id_operation_0"><input checked="checked" type="radio" class="radio" name="operation"
                                                           value="+" required id="id_operation_0">
                            +</label></div>
                    <div class="ball">
                        <label for="id_operation_1"><input type="radio" class="radio" name="operation" value="-"
                                                           required id="id_operation_1">
                            -</label></div>
                    <div class="ball">
                        <label for="id_operation_2"><input class="radio" type="radio" name="operation" value="*"
                                                           required id="id_operation_2">
                            *</label></div>
                    <div class="ball">
                        <label for="id_operation_3"><input type="radio" class="radio" name="operation" value="/"
                                                           required id="id_operation_3">
                            /</label></div>
                    <div class="ball">
                        <label class="ball" for="id_operation_4"><input type="radio" class="radio" name="operation"
                                                                        value="%" required id="id_operation_4">
                            %</label></div>
                </div>
                </li>
            </ul>
            </p>
            <p><label class="number" for="id_maximum_number_of_first_factor">Maximum number of first factor:</label>
                <input type="number" class="input" name="maximum_number_of_first_factor" required
                       id="id_maximum_number_of_first_factor"></p>
            <p><label class="number" for="id_minimum_number_of_first_factor">Minimum number of first factor:</label>
                <input type="number" class="input" name="minimum_number_of_first_factor" required
                       id="id_minimum_number_of_first_factor"></p>
            <p><label class="number" for="id_maximum_number_of_second_factor">Maximum number of second factor:</label>
                <input type="number" class="input" name="maximum_number_of_second_factor" required
                       id="id_maximum_number_of_second_factor"></p>
            <p><label class="number" for="id_minimum_number_of_second_factor">Minimum number of second factor:</label>
                <input type="number" class="input" name="minimum_number_of_second_factor" required
                       id="id_minimum_number_of_second_factor"></p>
            <button type="submit" class="submit">Confirm options</button>
        </form>
    </div>
{% endblock %}

final_project_django/final_project_app/templates/final_project_app/game_details.html
{% extends 'final_project_app/base.html' %}
{% block title %}Game details{% endblock %}
{% block content %}
    <div class="form_error">
        {{ error }}
        {% if form.errors %}
            {% for error in form.non_field_errors %}
                <p class="label-danger">{{ error|escape }}</p>
            {% endfor %}
        {% endif %}
    </div>

    <div class="details">
        <div class="details_container">
            <table>
                <div class="title">Game details</div>
                <tr>
                    <td class="nbt">Name of Game</td>
                    <td class="nbt">Date</td>
                    <td class="nbt">Operator</td>
                    <td class="nbt">Range First Factor</td>
                    <td class="nbt">Range Second Factor</td>
                    <td class="nbt">Correct Answers</td>
                    <td class="nbt">Wrong Answers</td>
                    <td class="nbt">Precision</td>
                    <td class="nbt">User</td>
                </tr>
                <tr>
                    <td>{{ name }}</td>
                    <td>{{ date }}</td>
                    <td>{{ operator }}</td>
                    <td>{{ range1_min }}-{{ range1_max }}</td>
                    <td>{{ range2_min }}-{{ range2_max }}</td>
                    <td>{{ number_of_correct_answers }}</td>
                    <td>{{ number_of_wrong_answers }}</td>
                    <td>{{ precision }}%</td>
                    <td>{{ user_id }}</td>
                </tr>
            </table>
            <div class="title">
                <button type="submit" class="button"><a class="ter" href="{% url 'games' user.id %}">Show my
                    games</a></button>
            </div>
        </div>
    </div>


    <div class="details">
        <div class="details_container details_container_small">
            <form method="post">
                {% csrf_token %}
                {#                {{ form.as_p }}#}
                {#                <!-- <input type="submit" value="Set name"> -->#}
                <div class="big_title"><label for="id_name_of_this_game">Set name:</label> <input
                        class="input small_input" type="text" name="name_of_this_game" maxlength="64" required
                        id="id_name_of_this_game">
                    <button type="submit" class="button">Show answer</button>
                </div>

            </form>

            <table class="distance">
                <th>Answers</th>
                <tr>
                    <td>first_factor</td>
                    <td>second_factor</td>
                    <td>answer (your one)</td>
                    <td>correct_answer</td>
                    <td>was_this_answer_correct</td>
                </tr>
                {% for answer in answers %}
                    <tr>
                        <td>
                            {{ answer.first_factor }}
                        </td>
                        <td>
                            {{ answer.second_factor }}
                        </td>
                        <td>
                            {{ answer.answer }}
                        </td>
                        <td>
                            {{ answer.correct_answer }}
                        </td>
                        <td>
                            {{ answer.was_this_answer_correct }}
                        </td>
                    </tr>
                {% endfor %}
            </table>
{% endblock %}

final_project_django/final_project_app/templates/final_project_app/games.html
{% extends 'final_project_app/base.html' %}
{% block title %}Games{% endblock %}
{% block content %}
    <div class="table_flex">
        <div class="table_container">
            <table>
                <th>Games</th>
                <tr>
                    <td>Name</td>
                    <td>Date</td>
                    <td>Number of answers</td>
                </tr>
                {% for game in games %}
                    <tr>
                        <td>
                            <a class="" href="{% url 'game_details' game_id=game.id %}">{{ game.name }}</a>
                        </td>
                        <td>
                            {{ game.date }}
                        </td>
                        <td>
                            {{ game.gameanswers_set.all.count }}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

final_project_django/final_project_app/templates/final_project_app/login.html
{% extends 'final_project_app/base.html' %}
{% block title %}Log in{% endblock %}
{% block content %}
    <div class="flex">
        <div class="container">
            <form method="post" class="form" id="login">
                {% csrf_token %}
                <h1 class="title">Log In</h1>
                <div class="form_error">
                    {{ error }}
                    {% if form.errors %}
                        {% for error in form.non_field_errors %}
                            <p class="label-danger">{{ error|escape }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="input-group">
                    <p><input required class="input marginsign" type="text" autofocus placeholder="Username"
                              name="login"
                              id="id_login">
                    </p>
                </div>
                <div class="input-group">
                    <p><input required class="input marginsign" autofocus type="password" placeholder="Password"
                              name="password"
                              id="id_password"></p>
                </div>
                <button type="submit" class="submit marginlogin">Continue</button>
                <p class="links">
                    <a href="{% url 'register' %}">Don't have an account? Sign up.</a>
                </p>
            </form>
        </div>
    </div>
{% endblock %}

final_project_django/final_project_app/templates/final_project_app/play.html
{% extends 'final_project_app/base.html' %}
{% block title %}Play{% endblock %}
{% block content %}
    <div class="answer_container">
        <p class="elo">What is {{ first }} {{ operator }} {{ second }}?</p>
        <div class="form_error">
            {{ error }}
            {% if form.errors %}
                {% for error in form.non_field_errors %}
                    <p class="label-danger">{{ error|escape }}</p>
                {% endfor %}
            {% endif %}
        </div>
        <form method="post">
            {% csrf_token %}
            <p>
                <label class="answer" for="id_answer">Answer:</label>
                <input class="input" type="number" name="answer" id="id_answer">
                <input type="hidden" name="answer_id" value="{{ answer_id }}" id="id_answer_id">
            </p>
            <input type="hidden" value="{{ first }}" name="first">
            <input type="hidden" value="{{ operator }}" name="operator">
            <input type="hidden" value="{{ second }}" name="second">
            <input class="submit space" name="btn" type="submit" value="Check">
            <input class="submit" name="btn" type="submit" value="Stop">
        </form>
    </div>
{% endblock %}

final_project_django/final_project_app/templates/final_project_app/register.html
{% extends 'final_project_app/base.html' %}
{% block title %}Sign Up{% endblock %}
{% block content %}
    <div class="flex">
        <div class="container">
            <form method="post" class="form" id="signup">
                {% csrf_token %}
                <h1 class="title">Sign Up</h1>
                <div class="form_error">
                    {{ error }}
                    {% if form.errors %}
                        {% for error in form.non_field_errors %}
                            <p class="label-danger">{{ error|escape }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
                <p><input class="input marginsign"
                          placeholder="Username" type="text"
                          name="username" required id="id_username">
                </p>
                <p><input class="input marginsign"
                          placeholder="First name" type="text"
                          name="first_name" required
                          id="id_first_name"></p>
                <p><input class="input marginsign"
                          placeholder="Last name" type="text"
                          name="last_name" required id="id_last_name">
                </p>
                <p><input class="input marginsign" placeholder="Email"
                          type="email" name="email" required
                          id="id_email"></p>
                <p><input class="input marginsign"
                          placeholder="Password" type="password"
                          name="password" required id="id_password"></p>
                <p><input class="input marginsign"
                          placeholder="Password again"
                          type="password"
                          name="password_again" required
                          id="id_password_again"></p>
                <button type="submit" class="submit">Continue</button>
                <p class="links">
                    <a href="{% url 'log_in' %}">Already have an account? Sign in!</a>
                </p>
            </form>
        </div>
    </div>


    {#    <form method="post">#}
    {#        {{ error }}#}
    {#        {% csrf_token %}#}
    {#        {{ form.as_p }}#}
    {# you need to make all fields required, do the hybrid #}
    {# you need to make 2 inputs for password and you have to check if both of these is the same (maybe use js) #}
    {#        <input type="submit" value="Sign Up">#}
    {#    </form>#}
{% endblock %}